### ISSUE TITLE
Please !

### ISSUE THREAD

**Issue by rogerioronin** [niuus/Descent-Wii#2]
How can you make available a version of "NeoGeo CD Redux" "https://github.com/emukidid/neogeo-cd-redux/releases" that works Classic Controller?

Tem como você disponibilizar uma versão do "NeoGeo CD Redux" "https://github.com/emukidid/neogeo-cd-redux/releases" que funcione Classic Controller?

**Comment by niuus** [comment]
> How can you make available a version of "NeoGeo CD Redux" "https://github.com/emukidid/neogeo-cd-redux/releases" that works Classic Controller?
> 
> Tem como você disponibilizar uma versão do "NeoGeo CD Redux" "https://github.com/emukidid/neogeo-cd-redux/releases" que funcione Classic Controller?

**Completely unrelated** to Descent Wii, NOT an issue. Closing.
